version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "nx"
      - dependency-name: "@nx/*"
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-eslint/*"
      - dependency-name: "@codingame/*"
      - dependency-name: "monaco-languageclient"
      - dependency-name: "vscode-languageclient"
      - dependency-name: "vscode-languageserver"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
      production:
        dependency-type: production
      development:
        dependency-type: development
