name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      # Build Angular app
      - name: Build
        run: pnpm web:build # --base-href=/stc-23/
      # Allow routing on GitHub Pages
      - name: Create 404.html
        run: cp dist/apps/web/index.html dist/apps/web/404.html
      # https://github.com/actions/starter-workflows/blob/main/pages/static.yml
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/apps/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
